//generated by omni sharp
using System.Runtime.Serialization;

namespace expression_evaluator;

[Serializable]
internal class SyntaxException : Exception
{
    public SyntaxException()
    {
    }

    public SyntaxException(string? message) : base(message)
    {
    }

    public SyntaxException(string? message, Exception? innerException) : base(message, innerException)
    {
    }

    protected SyntaxException(SerializationInfo info, StreamingContext context) : base(info, context)
    {
    }
}